### ISSUE TITLE
Producs - 2-1 (Desktop)

### ISSUE THREAD

**Issue by zblock** [not-the-droids/Finesse#16] opened 2020-11-09 03:30 UTC
Products - 2-1 D - https://xd.adobe.com/view/06e309e3-53d4-49b2-b716-c566752f3063-53b0/screen/48414c53-6f62-4e94-9c29-79b94d13a313

**Comment by aceiii** [comment] 2020-11-13 16:44
This screen looks exactly like the one at #15.

**Comment by ohlin** [comment] 2020-11-13 20:06
Duplicate of #15

**Closed by ohlin** 2020-11-13 20:06 UTC
Labels: duplicate
