### ISSUE TITLE
Check Out (Mobile/Desktop)

### ISSUE THREAD

**Issue by zblock** [not-the-droids/Finesse#18] opened 2020-11-09 03:31 UTC
Check Out D - https://xd.adobe.com/view/06e309e3-53d4-49b2-b716-c566752f3063-53b0/screen/e29bac24-cce0-4739-980f-30b755fe527e

--------
Check Out M - https://xd.adobe.com/view/cc4d499b-422b-423b-9ee7-da3d0482d991-991e/screen/f5e6bc9e-83e2-4bf1-ab4f-d537e1054167

**Comment by NeseemGit** [comment] 2020-11-12 23:59
Duplicate of ticket #36

**Closed by NeseemGit** 2020-11-12 23:59 UTC
